export const productsData = [
  {
    id: 1,
    title: 'APT-HD720 ROTARY HAMMER',
    sku: 'SKU: IND-RT-720-B',
    category: 'POWER TOOLS',
    subcategory: 'POWER TOOLS / ROTARY',
    price: 8450.00,
    image: '/assets/png/products/rotary_hammer.png',
    badge: 'IN STOCK',
    badgeType: 'success', // Green
    popularity: 95,
  },
  {
    id: 2,
    title: 'APT-WELD PRO 250X',
    sku: 'SKU: WLD-MIG-250X',
    category: 'WELDING EQUIPMENT',
    subcategory: 'WELDING / MIG',
    price: 32500.00,
    image: '/assets/png/products/mig_welder.png',
    badge: 'BEST SELLER',
    badgeType: 'warning', // Orange/Yellow
    popularity: 98,
  },
  {
    id: 3,
    title: 'STORM-PUMP 180 BAR',
    sku: 'SKU: CLN-HP-180',
    category: 'CLEANING SOLUTIONS',
    subcategory: 'CLEANING / HIGH PRESSURE',
    price: 14200.00,
    image: '/assets/png/products/pressure_washer.png',
    badge: 'IN STOCK',
    badgeType: 'success',
    popularity: 88,
  },
  {
    id: 4,
    title: 'SMOOTH-EDGE 82MM',
    sku: 'SKU: IND-PLN-82',
    category: 'POWER TOOLS',
    subcategory: 'POWER TOOLS / PLANER',
    price: 5500.00,
    image: '/assets/png/products/electric_planer.png',
    badge: 'IN STOCK',
    badgeType: 'success',
    popularity: 76,
  },
  {
    id: 5,
    title: 'AIR-MAXX 50L BELT',
    sku: 'SKU: ACC-BT-50L',
    category: 'AIR COMPRESSORS',
    subcategory: 'EQUIPMENT / AIR COMPRESSOR',
    price: 18500.00,
    image: '/assets/png/products/air_compressor.png',
    badge: 'IN STOCK',
    badgeType: 'success',
    popularity: 92,
  },
  {
    id: 6,
    title: 'APT-CUT 4-INCH PRO',
    sku: 'SKU: IND-GR-04P',
    category: 'POWER TOOLS',
    subcategory: 'POWER TOOLS / GRINDING',
    price: 3450.00,
    image: '/assets/png/products/angle_grinder.png',
    badge: 'IN STOCK',
    badgeType: 'success',
    popularity: 84,
  },
  {
    id: 7,
    title: 'APT-AGRI TILLER 7HP',
    sku: 'SKU: AGR-TL-07HP',
    category: 'AGRI TOOLS',
    subcategory: 'AGRI / TILLERS',
    price: 42000.00,
    image: '/assets/png/products/power_tiller.png',
    badge: 'IN STOCK',
    badgeType: 'success',
    popularity: 90,
  },
  {
    id: 8,
    title: 'LASER-SCAN PRO 40M',
    sku: 'SKU: MST-LS-40M',
    category: 'MEASURING INSTRUMENTS',
    subcategory: 'MEASURING / DIGITAL',
    price: 4500.00,
    image: '/assets/png/products/laser_measurer.png',
    badge: 'NEW ARRIVAL',
    badgeType: 'danger', // Red
    popularity: 82,
  },
  {
    id: 9,
    title: 'APT-CORDLESS DRILL 18V',
    sku: 'SKU: IND-CD-18V',
    category: 'POWER TOOLS',
    subcategory: 'POWER TOOLS / DRILLS',
    price: 4200.00,
    image: '/assets/png/products/rotary_hammer.png',
    badge: 'BEST SELLER',
    badgeType: 'warning',
    popularity: 89,
  },
  {
    id: 10,
    title: 'TIG-ARC PRO 200',
    sku: 'SKU: WLD-TIG-200',
    category: 'WELDING EQUIPMENT',
    subcategory: 'WELDING / TIG',
    price: 28900.00,
    image: '/assets/png/products/mig_welder.png',
    badge: 'IN STOCK',
    badgeType: 'success',
    popularity: 79,
  },
  {
    id: 11,
    title: 'CYCLONE VACUUM 30L',
    sku: 'SKU: CLN-VC-30L',
    category: 'CLEANING SOLUTIONS',
    subcategory: 'CLEANING / DRY-WET',
    price: 9800.00,
    image: '/assets/png/products/pressure_washer.png',
    badge: 'NEW ARRIVAL',
    badgeType: 'danger',
    popularity: 81,
  },
  {
    id: 12,
    title: 'DIGITAL CALIPER 150MM',
    sku: 'SKU: MST-DC-150',
    category: 'MEASURING INSTRUMENTS',
    subcategory: 'MEASURING / CALIPER',
    price: 1850.00,
    image: '/assets/png/products/laser_measurer.png',
    badge: 'IN STOCK',
    badgeType: 'success',
    popularity: 75,
  }
];
